version: '3.8'

services:
  web:
    image: game-img:latest
    container_name: my-game-cont
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/usr/share/nginx/html
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
