apiVersion: app/v1
kind: Deployment
metadata:
  name: my-game-deploy
  labels:
    app: game-app
spec: 
  selector:
    matchlabels:
      app: game-app
  replicas: 4
  template:
    metadata:
      name: my-game-pod
      label:
        app: game-app
    spec:
      containers:
        - name: nginx-container
          image: game-img:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 200m
              memory: 100M
            limits:
              cpu: 500m
              memory: 200M



